name: MASD-YOLO
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=25.1
  - pytorch=2.0.0
  - torchvision=0.15.1
  - cudatoolkit=11.8
  - numpy=1.26.4
  - matplotlib=3.9.4
  - pandas=2.3.1
  - pillow=11.3.0
  - pyyaml=6.0.2
  - requests=2.32.4
  - scipy=1.13.1
  - seaborn=0.13.2
  - tqdm=4.67.1
  - psutil=7.0.0
  - pip:
      - einops==0.8.1
      - mmengine==0.10.7
      - opencv-python==4.8.1.78
      - pycocotools==2.0.7
      - thop==0.1.1.post2209072238
